---
- hosts: all
  vars:
    scala_version: 2.9.3
    sbt_version: 0.13.5
    zookeeper_version: 3.4.6
    kafka_version: 0.8.1.1
  

  tasks:
    - include: tasks/install-java.yml
    - include: tasks/install-scala.yml
    - include: tasks/install-sbt.yml
    - include: tasks/install-zookeeper.yml  
    - include: tasks/install-kafka.yml

